services:
  litepan:
    image: ghcr.io/zhemed/litepan:v0.0.48
    container_name: litepan
    restart: unless-stopped
    ports:
      - "5211:5211"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
