services:
  litepan:
    image: ghcr.io/zhemed/litepan:v0.0.8
    container_name: litepan
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /vol1/1000/docker/litepango/data:/app/data
      - /vol1/1000/docker/litepango/mounts:/app/mounts:shared
    devices:
      - /dev/fuse:/dev/fuse
    privileged: true
    pid: "host"
    network_mode: "host"
    restart: always
