services:
  litepan:
    image: ghcr.io/zhemed/litepan:v0.0.45
    container_name: litepan
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /vol1/1000/docker/litepan/data:/app/data
    network_mode: "host"
    restart: always
